TalDorAdi/Controllers/BranchController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Linq;
using TalDorAdi.Dal;
using TalDorAdi.Models;

namespace TalDorAdi.Controllers
{
    public class BranchController : Controller
    {
        private readonly DataLayer _context;
        public BranchController(DataLayer context)
        {
            _context = context;
        }
        // GET: Branch
        public ActionResult Index()
        {
            return View();
        }

        public ViewResult ShowMapToSupplier()
        {
            HttpContext.Session.SetString("PageTitle", "Our Branches");
            return View();
        }

        public ViewResult ShowMapToManager()
        {
            HttpContext.Session.SetString("PageTitle", "Our Branches");
            return View();
        }

        [HttpGet]
        public JsonResult getLocations()
        {
            List<Location> objLocations = _context.Locations.ToList<Location>();
            return Json(objLocations);
        }

        [HttpPost]
        public JsonResult addLocation(Location loc)
        {
            List<Location> objLocations =
             (from a in _context.Locations
              where (a.coordinates.Equals(loc.coordinates))
              select a).ToList<Location>();
            
            if (objLocations.Count == 0)
            {
                _context.Locations.Add(loc);

                try
                {
                    _context.SaveChanges();
                }
                catch (DbEntityValidationException ex)
                {
                    ViewBag.Error = TempData["there was problem. please try again"];
                }
            }

            else ViewBag.Error = TempData["There is branch in this place"];
            
            objLocations = _context.Locations.ToList<Location>();

            return Json(objLocations);
        }

    }
}

TalDorAdi/Controllers/OrderController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using TalDorAdi.Dal;
using TalDorAdi.Models;
using TalDorAdi.ViewModel;

namespace TalDorAdi.Controllers
{

    [Route("[controller]/[action]")]
    [ApiController]
    public class OrderController : Controller
    {

        private readonly DataLayer _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public OrderController(IWebHostEnvironment webHostEnvironment, DataLayer context)
        {
            _webHostEnvironment = webHostEnvironment;
            _context = context;
        }
        // GET: Order
        public ViewResult Index()
        {
            return View();
        }

        // web service!!
        public async Task<JsonResult> GetCurrentDollarJson(string currCoin)
        {
            try {
                HttpClient client = new HttpClient();
                var responseString = await client.GetStringAsync("https://api.exchangeratesapi.io/latest?symbols=" + currCoin);
                return Json(responseString);
            }
            catch(Exception ex)
            {
                return Json(1);
            }
            
        }

        public ActionResult ShowOrders()//return view of show orders page
        {
            if (HttpContext.Request.Cookies["Manager"] != null)
            {
                HttpContext.Session.SetString("PageTitle", "Orders");
                return View();
            }
            else
            {
                return RedirectToAction("ShowSignInPage", "Auth");
            }
        }

        // Join
        private IEnumerable<OrderProductViewModel> GetOrderedProducts()
        {
            List<Order> objOrders = _context.Orders.ToList<Order>();
            List<Product> objProducts = _context.Products.ToList<Product>();
            var orderProductViewModel = from product in objProducts
                                        join order in objOrders
                                        on product.productID equals order.productID
                                        into result
                                        from newOrder in result.DefaultIfEmpty()
                                        select new OrderProductViewModel { product = product, order = newOrder };
            return orderProductViewModel;
        }
        public JsonResult GetOrderByJson()//return json with all the current orders
        {
            var orderedProducts = GetOrderedProducts();
            return Json(orderedProducts);
        }
        public ActionResult ShowReservationPage()
        {
            if (HttpContext.Request.Cookies["Supplier"] != null)
            {
                String data = Request.Cookies["Supplier"];
                User user = new User();
                user.userID = (String)JObject.Parse(data)["userID"];
                user.name = (String)JObject.Parse(data)["name"];
                user.permission = (int)JObject.Parse(data)["permission"];
                user.password = (String)JObject.Parse(data)["password"];
                HttpContext.Session.SetString("LogginInUser", user.name);
                HttpContext.Session.SetString("PageTitle", "New Order");
                return View(user);
            }
            else
            {
                return RedirectToAction("ShowSignInPage", "Auth");
            }


        }
        public JsonResult MakeOrder()
        {
            Order o = new Order();
            o.productID = Request.Form["txtProductID"];//Taking information from the form
            o.supplierID = Request.Form["txtUserID"];
            o.amount = Int32.Parse(Request.Form["txtOption"]);
            o.orderDate = DateTime.Now.ToString("dd-MM-yyyy hh:mm:ss tt"); ;

            ViewBag.Error = TempData[""];

            //DataLayer Pdal = new DataLayer();
            List<Product> objProducts =
             (from x in _context.Products
              where (x.productID.Equals(o.productID))//Finding the desired product in data base
              select x).ToList<Product>();

            if ((objProducts[0].initialAmount >= o.amount))//If there is enough in stock you can to buy
            {
                List<Order> objO = _context.Orders.ToList<Order>();
                //find the max orderID
                var maxOrderID = -1;
                foreach (Order order in objO)
                {
                    if (Int32.Parse(order.orderID) > maxOrderID)
                    {
                        maxOrderID = Int32.Parse(order.orderID);
                    }
                }
                o.orderID = (maxOrderID + 1).ToString();
                //o.productName = objProducts[0].productName;
                objProducts[0].initialAmount -= o.amount;
                _context.Orders.Add(o);//add order to data base

                try
                {
                    _context.SaveChanges();
                }
                catch (DbEntityValidationException ex)
                {
                    ViewBag.Error = TempData["there was problem. please try again"];
                }
            }
            else ViewBag.Error = TempData["not enough in stock"];
            List<Order> objOrders = _context.Orders.ToList<Order>();
            objProducts = _context.Products.ToList<Product>();
            groupUsersAndProducts();
            return Json(objProducts);//return json with all the current products 
        }

        [HttpDelete]
        public JsonResult DeleteOrderByJson([FromQuery]string id)
        {
            List<Order> objOrders =
               (from x in _context.Orders
                where (x.orderID.Equals(id.ToString()))
                select x).ToList<Order>();
            if (objOrders.Count == 1)
            {
                _context.Orders.Remove(objOrders[0]);
                _context.SaveChanges();//update data base
            }
            return GetOrderByJson();
        }

        [HttpPut]
        public JsonResult ChangeOrderAmount([FromQuery]string id, [FromQuery]string orderAmount, [FromQuery]string newAmount)
        {
            List<Order> objOrders =
               (from x in _context.Orders
                where (x.orderID.Equals(id.ToString()))
                select x).ToList<Order>();
            if (objOrders == null) return null;
            var productID = objOrders.First().productID;
            //change the product amount left
            List<Product> productToEdit =
             (from x in _context.Products
              where (x.productID.Equals(productID))//Finding the desired product in data base
              select x).ToList<Product>();
            // current amount = DB amount + amount that were ordered(return the bought) - the new amount bought;
            productToEdit.First().initialAmount = productToEdit.First().initialAmount + Int32.Parse(orderAmount) - Int32.Parse(newAmount);
            //update the order amount
            objOrders.First().amount = Int32.Parse(newAmount);
            _context.SaveChanges();//update data base

            return GetOrderByJson();
        }
        [HttpPost]
        public JsonResult SearchOrder([FromQuery]string productID, [FromQuery]string productName, [FromQuery]string supplierID)
        {
            var orderedProducts = GetOrderedProducts();
            List<OrderProductViewModel> results = null;


            if (productID == "All" && productName == "All" && supplierID == null)
            {
                return Json(orderedProducts);
            }

            results =
                (from x in orderedProducts
                where (x.order != null) && ((productID != "All" ? x.product.productID.Equals(productID) : true) && (productName != "All" ? x.product.productType.Equals(productName) : true)
                && (supplierID != null ? (x.order != null && x.order.supplierID.Equals(supplierID)) : true))
                select x).ToList();

            return Json(results);
        }

        private void groupUsersAndProducts()
        {
            IEnumerable<string> suppliersIds =
               (from x in _context.Orders
                select x.supplierID).ToList().Distinct();

            IEnumerable<Order> orders =
               (from x in _context.Orders
                select x).ToList().Distinct();

            IEnumerable<string> products =
               (from x in _context.Products
                select x.productID);

            List<string> usedProducts = new List<string>();

            foreach (string supplierId in suppliersIds)
            {
                var str = "";
                foreach (string productId in products)
                {
                    var order = orders.FirstOrDefault(order => order.productID == productId && order.supplierID == supplierId);
                    int existSign;
                    if (order != null)
                    {
                        existSign = 1;
                    }
                    else
                    {
                        existSign = 0;
                    }
                    if (str.Length == 0)
                    {
                        str += existSign;
                    }
                    else
                    {
                        str += "," + existSign;
                    }
                }
                usedProducts.Add(str);
            }

            updateOrdersHistory(suppliersIds.ToArray(), products.ToArray(), usedProducts.ToArray());
        }

        private void updateOrdersHistory(string[] suppliersIds, string[] products, string[] usedProducts)
        {
            string fileName = "OrdersHistory.csv";
            var joinIds = String.Join(",", products.ToArray());
            using (System.IO.StreamWriter file =

TalDorAdi/Views/Shared/MDB.cshtml
 <!-- Font Awesome -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
<!-- Bootstrap core CSS -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
<!-- Material Design Bootstrap -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.10/css/mdb.min.css" rel="stylesheet">

<!-- JQuery -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.10/js/mdb.min.js"></script>
<link href="css/addons/flag.min.css" rel="stylesheet">

TalDorAdi/Views/Shared/ManagerNavbar.cshtml
@using Microsoft.AspNetCore.Http;

﻿<nav class="mb-3 navbar navbar-expand-lg navbar-dark default-color">
    <span class="navbar-brand">
        <img width="26" src="~/Content/img/logo-black.png" />
        <span class="title" style="margin-left:3px; margin-top:2px">@Context.Session.GetString("PageTitle")</span>
    </span>

    <div class="collapse navbar-collapse first-nav">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("ShowManagerPage", "Manager")">
                    <i class="fas fa-home fa-lg"></i> DashBoard
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("ShowMapToManager","Branch")">
                    <i class="fas fa-map-marker-alt fa-lg"></i> Branches
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("ShowStock","Product")">
                    <i class="fas fa-layer-group fa-lg"></i> Stock
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("ShowOrders","Order")">
                    <i class="fas fa-file-invoice-dollar fa-lg"></i>  Orders
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("ShowSuppliers","Supplier")">
                    <i class="fas fa-address-book fa-lg"></i>  Suppliers
                </a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto nav-flex-icons">
            <li class="nav-item facebook-icon">
                <nav>
                    <a class="waves-effect waves-light" href="https://www.facebook.com/DAT-Shop-101816628299277">
                        <i class="fab fa-facebook fa-lg"></i>
                    </a>
                </nav>
            </li>

            <li class="nav-item span">
                <div>
                    Welcome Back @Context.Session.GetString("LogginInUser")!
                </div>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link user-nav">
                    <i class="fas fa-user"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right">
                    <a class="dropdown-item" href="@Url.Action("ShowProfilePage","Profile")">
                        <i class="fas fa-id-card fa-lg"></i><span class="label">Profile</span>
                    </a>
                    <a class="dropdown-item" href="@Url.Action("ShowSignInPage","Auth")">
                        <i class="fas fa-sign-out-alt"></i><span class="label">Log Out</span>
                    </a>
                </div>
            </li>
        </ul>
    </div>
</nav>

TalDorAdi/Views/Shared/Navbar.cshtml
@using Microsoft.AspNetCore.Http;
﻿
<nav class="navbar navbar-expand-lg navbar-dark fixed-top">
    <div class="container">
        <span class="navbar-brand">
            <img width="26" src="~/Content/img/logo-black.png" />
            <span class="title" style="margin-left:3px; margin-top:2px">@Context.Session.GetString("PageTitle")</span>
        </span>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item" id="home-nav-item">
                    <a class="nav-link" href="@Url.Action("ShowHomePage","Home")">
                        Home
                    </a>
                </li>
                <li class="nav-item" id="signin-nav-item">
                    <a class="nav-link" href="@Url.Action("ShowSignInPage","Auth")">Sign In</a>
                </li>
                <li class="nav-item" id="signup-nav-item">
                    <a class="nav-link" href="@Url.Action("ShowSignUpPage","Auth")">Sign Up</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

TalDorAdi/Views/Shared/SupplierNavbar.cshtml
@using Microsoft.AspNetCore.Http;
﻿
<nav class="mb-3 navbar navbar-expand-lg navbar-dark default-color">
    <span class="navbar-brand">
        <img width="26" src="~/Content/img/logo-black.png" />
        <span class="title" style="margin-left:3px; margin-top:2px">@Context.Session.GetString("PageTitle")</span>
    </span>

    <div class="collapse navbar-collapse first-nav">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("ShowSupplierPage","Supplier")">
                    <i class="fas fa-home fa-lg"></i> DashBoard
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("ShowReservationPage","Order")">
                    <i class="fas fa-clipboard-list fa-lg"></i>  New Order
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("ShowMyReservations","Supplier")">
                    <i class="fas fa-shopping-cart fa-lg"></i>  My Cart
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("ShowMapToSupplier","Branch")">
                    <i class="fas fa-map-marker-alt fa-lg"></i>  Branches
                </a>
            </li>

        </ul>
        <ul class="navbar-nav ml-auto nav-flex-icons">
            <li class="nav-item facebook-icon">
                <nav>
                    <a class="waves-effect waves-light" href="https://www.facebook.com/DAT-Shop-101816628299277">
                        <i class="fab fa-facebook fa-lg"></i>
                    </a>
                </nav>

            </li>
            <li class="nav-item span">
                <div>
                    Welcome Back @Context.Session.GetString("LogginInUser")!
                </div>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link user-nav">
                    <i class="fas fa-user"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right">
                    <a class="dropdown-item" href="@Url.Action("ShowProfilePage","Profile")">
                        <i class="fas fa-id-card fa-lg"></i><span class="label">Profile</span>
                    </a>
                    <a class="dropdown-item" href="@Url.Action("ShowSignInPage","Auth")">
                        <i class="fas fa-sign-out-alt"></i><span class="label">Log Out</span>
                    </a>
                </div>
            </li>
        </ul>
    </div>
</nav>

TalDorAdi/Views/Shared/_Layout.cshtml
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @Html.Partial("MDB")
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
          crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<body>
    <div class="view">
        <div class="mask rgba-gradient align-items-center">
            <div class="container">
                <!--Grid row-->
                <div class="mask rgba-gradient align-items-center">
                    <div class="container">
                        
                        <div class="container body-content">
                            @RenderBody()
                        </div>
                        <div class="navbar-collapse collapse">
                            <ul class="nav navbar-nav">
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>



</body>
</html>